<?php

namespace ContainerTqdv9S7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N5EKdE5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N5EKdE5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N5EKdE5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'planet' => ['privates', '.errored..service_locator.N5EKdE5.App\\Entity\\Planet', NULL, 'Cannot autowire service ".service_locator.N5EKdE5": it needs an instance of "App\\Entity\\Planet" but this type has been excluded in "config/services.yaml".'],
        ], [
            'planet' => 'App\\Entity\\Planet',
        ]);
    }
}
