<?php

namespace ContainerTqdv9S7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_35hoKMeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.35hoKMe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.35hoKMe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\MainController::homepage' => ['privates', '.service_locator.YPaS.rr', 'get_ServiceLocator_YPaS_RrService', true],
            'App\\Controller\\PlanetController::delete' => ['privates', '.service_locator.Vw61GZ9', 'get_ServiceLocator_Vw61GZ9Service', true],
            'App\\Controller\\PlanetController::edit' => ['privates', '.service_locator.Vw61GZ9', 'get_ServiceLocator_Vw61GZ9Service', true],
            'App\\Controller\\PlanetController::index' => ['privates', '.service_locator.GIR4G0G', 'get_ServiceLocator_GIR4G0GService', true],
            'App\\Controller\\PlanetController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PlanetController::show' => ['privates', '.service_locator.N5EKdE5', 'get_ServiceLocator_N5EKdE5Service', true],
            'App\\Controller\\VoyageController::delete' => ['privates', '.service_locator.0aFFzDT', 'get_ServiceLocator_0aFFzDTService', true],
            'App\\Controller\\VoyageController::edit' => ['privates', '.service_locator.0aFFzDT', 'get_ServiceLocator_0aFFzDTService', true],
            'App\\Controller\\VoyageController::index' => ['privates', '.service_locator.aDkPpL7', 'get_ServiceLocator_ADkPpL7Service', true],
            'App\\Controller\\VoyageController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\VoyageController::show' => ['privates', '.service_locator.cRw86ao', 'get_ServiceLocator_CRw86aoService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\MainController:homepage' => ['privates', '.service_locator.YPaS.rr', 'get_ServiceLocator_YPaS_RrService', true],
            'App\\Controller\\PlanetController:delete' => ['privates', '.service_locator.Vw61GZ9', 'get_ServiceLocator_Vw61GZ9Service', true],
            'App\\Controller\\PlanetController:edit' => ['privates', '.service_locator.Vw61GZ9', 'get_ServiceLocator_Vw61GZ9Service', true],
            'App\\Controller\\PlanetController:index' => ['privates', '.service_locator.GIR4G0G', 'get_ServiceLocator_GIR4G0GService', true],
            'App\\Controller\\PlanetController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PlanetController:show' => ['privates', '.service_locator.N5EKdE5', 'get_ServiceLocator_N5EKdE5Service', true],
            'App\\Controller\\VoyageController:delete' => ['privates', '.service_locator.0aFFzDT', 'get_ServiceLocator_0aFFzDTService', true],
            'App\\Controller\\VoyageController:edit' => ['privates', '.service_locator.0aFFzDT', 'get_ServiceLocator_0aFFzDTService', true],
            'App\\Controller\\VoyageController:index' => ['privates', '.service_locator.aDkPpL7', 'get_ServiceLocator_ADkPpL7Service', true],
            'App\\Controller\\VoyageController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\VoyageController:show' => ['privates', '.service_locator.cRw86ao', 'get_ServiceLocator_CRw86aoService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\MainController::homepage' => '?',
            'App\\Controller\\PlanetController::delete' => '?',
            'App\\Controller\\PlanetController::edit' => '?',
            'App\\Controller\\PlanetController::index' => '?',
            'App\\Controller\\PlanetController::new' => '?',
            'App\\Controller\\PlanetController::show' => '?',
            'App\\Controller\\VoyageController::delete' => '?',
            'App\\Controller\\VoyageController::edit' => '?',
            'App\\Controller\\VoyageController::index' => '?',
            'App\\Controller\\VoyageController::new' => '?',
            'App\\Controller\\VoyageController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\MainController:homepage' => '?',
            'App\\Controller\\PlanetController:delete' => '?',
            'App\\Controller\\PlanetController:edit' => '?',
            'App\\Controller\\PlanetController:index' => '?',
            'App\\Controller\\PlanetController:new' => '?',
            'App\\Controller\\PlanetController:show' => '?',
            'App\\Controller\\VoyageController:delete' => '?',
            'App\\Controller\\VoyageController:edit' => '?',
            'App\\Controller\\VoyageController:index' => '?',
            'App\\Controller\\VoyageController:new' => '?',
            'App\\Controller\\VoyageController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
