<?php

namespace ContainerTqdv9S7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0aFFzDTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0aFFzDT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0aFFzDT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'voyage' => ['privates', '.errored..service_locator.0aFFzDT.App\\Entity\\Voyage', NULL, 'Cannot autowire service ".service_locator.0aFFzDT": it needs an instance of "App\\Entity\\Voyage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'voyage' => 'App\\Entity\\Voyage',
        ]);
    }
}
