<?php

namespace ContainerTqdv9S7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlanetTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PlanetType' shared autowired service.
     *
     * @return \App\Form\PlanetType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PlanetType.php';

        return $container->privates['App\\Form\\PlanetType'] = new \App\Form\PlanetType();
    }
}
