<?php

namespace ContainerTqdv9S7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlanetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.N5EKdE5.App\Entity\Planet' shared service.
     *
     * @return \App\Entity\Planet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.N5EKdE5": it needs an instance of "App\\Entity\\Planet" but this type has been excluded in "config/services.yaml".');
    }
}
