<?php

namespace ContainerTqdv9S7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Runtime_TailwindService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'twig.runtime.tailwind' shared service.
     *
     * @return \TalesFromADev\Twig\Extra\Tailwind\TailwindRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/tales-from-a-dev/twig-tailwind-extra/src/TailwindRuntime.php';

        return $container->privates['twig.runtime.tailwind'] = new \TalesFromADev\Twig\Extra\Tailwind\TailwindRuntime(($container->services['twig.cache.tailwind'] ?? self::getTwig_Cache_TailwindService($container)));
    }
}
