<?php

namespace ContainerTqdv9S7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_Autocomplete_EntityAutocompleteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'ux.autocomplete.entity_autocomplete_controller' shared service.
     *
     * @return \Symfony\UX\Autocomplete\Controller\EntityAutocompleteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-autocomplete/src/Controller/EntityAutocompleteController.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-autocomplete/src/AutocompleterRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-autocomplete/src/AutocompleteResultsExecutor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-autocomplete/src/Doctrine/DoctrineRegistryWrapper.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-autocomplete/src/Checksum/ChecksumCalculator.php';

        return $container->services['ux.autocomplete.entity_autocomplete_controller'] = new \Symfony\UX\Autocomplete\Controller\EntityAutocompleteController(new \Symfony\UX\Autocomplete\AutocompleterRegistry(($container->privates['.service_locator.Xbsa8iG'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], []))), new \Symfony\UX\Autocomplete\AutocompleteResultsExecutor(new \Symfony\UX\Autocomplete\Doctrine\DoctrineRegistryWrapper(($container->services['doctrine'] ?? self::getDoctrineService($container))), ($container->privates['property_accessor'] ?? $container->load('getPropertyAccessorService')), NULL), ($container->services['router'] ?? self::getRouterService($container)), ($container->privates['ux.autocomplete.checksum_calculator'] ??= new \Symfony\UX\Autocomplete\Checksum\ChecksumCalculator($container->getEnv('APP_SECRET'))));
    }
}
