<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTqdv9S7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTqdv9S7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTqdv9S7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTqdv9S7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTqdv9S7\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tqdv9S7',
    'container.build_id' => '5f113746',
    'container.build_time' => 1716820648,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTqdv9S7');
